# Generated by Django 6.0.3 on 2026-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='No bio added.', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_user.png', null=True, upload_to='profile_pics'),
        ),
    ]
