# Generated by Django 6.0.3 on 2026-08-19 09:04

import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_remove_profile_followers_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_user.png', null=True, upload_to=ui.models.UploadPfp),
        ),
    ]
