# Generated by Django 6.0.3 on 2026-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
