# Generated by Django 6.0.3 on 2026-08-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medical_cert',
            field=models.ImageField(blank=True, null=True, upload_to='certs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='No bio added.', max_length=60),
        ),
    ]
